### Loopchan's Config File

guild = 1334179500384059456 # PTL Guild ID
owner = 908779319084589067  # Loopchan's Owner ID

global_cooldown = 3 # Cooldown for all commands (may be 0 to disable)

database_path = "loopchan.db" # Optional # Main Database Path (where users, economics, lastfm sessions tables are going to be stored in)

[roles]
qa = 1334803304403963965        # QA Role ID
staff = 1334231212851466311     # Staff Role ID
member = 1360707888900997332    # Member Role ID

[channels]
qa_forms = 1366382858649731103          # QA Forms Channel ID
unverified_chat = 1364308262517997568   # Unverified Chat Channel ID

[welcomecard]
enabled         = true                  # Should send welcomecard once user joins server?
channel         = 1368184484645572718   # Where to send welcomecard
react           = true                  # Should add reaction to welcomecard message?
react_id        = 1367090774453522502   # Reaction ID
react_name      = "wave"                # Reaction Name
react_animated  = true                  # Is reaction animated?

[progressbar_emojis] # Custom progress bar with emojis until ComponentsV2 support in serenity comes out # Please note that bot must be in the same server with emojis for it to work
[progressbar_emojis.empty] # Empty Progress Bar
start   = "<:LoopchanProgressbarStart:1368315378404429914>"     # Empty Progress Bar Start
mid     = "<:LoopchanProgressbarProgress:1368315376450146426>"  # Empty Progress Bar Mid (progress)
end     = "<:LoopchanProgressbarEnd:1368315369722351617>"       # Empty Progress Bar End
[progressbar_emojis.filled] # Filled Progress Bar
start   = "<:LoopchanProgressbarFillStart:1368315375048986817>"     # Filled Progress Bar Start
mid     = "<:LoopchanProgressbarFillProgress:1368315373547683980>"  # Filled Progress Bar Mid (progress)
end     = "<:LoopchanProgressbarFillEnd:1368315371278565491>"       # Filled Progress Bar End

[leveling]
max_exp_per_message                 = 40    # The max amount of exp you can get per message (excluding modifiers)
exp_multiplier                      = 1     # Base exp multiplier
double_multiplier_on_weekdays       = true  # Whenether or not to double exp gain on weekdays (Saturday, Sunday)
progrees_bar_size                   = 10    # Progressbar size in `/eco level`
progress_bar_in_leaderboard_size    = 8     # Progressbar size in `/eco leaderboard`

[economy] # TODO: Add more phrases
work_phrases = [
    "You've done some deliveries, avoiding enforcers, and gained **{} coins**.",
    "You've done some time trials and gained **{} coins** by selling medals.",
    "You've won a race against another runner, and they paid you **{} coins**.",
    "You've fought against an enforcer, and they had **{} coins** in their pockets.",
]
failed_work_phrases = [
    "You got caught by an enforcer while running and **could not complete a delivery**.",
    "You slipped while wallclimbing and **broke delivery package in process**.",
    "You've started a race against another runner, but **they were faster than you**.",
    "A patrol of **enforcers caught you while you were delivering** a package.",
]
work_fail_chance    = 0.1           # Work has a chance to fail, user will not receive any amount of coins if that happens (10%)
work_cooldown       = 20            # In minutes
work_payment        = [100, 200]    # A range of how much you get for /eco work (randomized)
shop_not_level_3_warn = false # Should warn about server not being boost level 3 in shop?
shop_items = [
    { id = 1376626127375962155, icon_id = 1376642201647583356, icon_name = "LoopchanTraceur", display_name = "Traceur", description = "An experienced runner", price = 500 },
    { id = 1376625906893848637, icon_id = 1376642240566263818, icon_name = "LoopchanElysium", display_name = "Elysium Employee", description = "An elysium employee that is allied with runners", price = 1499 },
    { id = 1376627136001085531, icon_id = 1376642267430781078, icon_name = "LoopchanEnforcer", display_name = "Enforcer", description = "An enforcer that protects city from crime & runners", price = 6942 },
    { id = 1376627238774247475, icon_id = 1376642282597646436, icon_name = "LoopchanPoslar", display_name = "Poslar", description = "evil.", price = 10000 },
]
fish_cooldown = 10   # In minutes
fishes = [
    { name = "Salmon", color = "FF7E70", description = "Classic.", base_value = 5, possible_modifiers = ["Golden", "Ginormous", "Big", "Rotten"] },
    { name = "Tuna", color = "59CCE3", description = "Holy moly, a Tuna! I wonder what at-tuna-ment it is?", base_value = 3, possible_modifiers = ["Golden", "Big", "Ginormous", "Rotten"] },
    { name = "Carp", color = "75959C", description = "Woah! An \"iron\" fish.. I wouldn't eat it.", base_value = 7, possible_modifiers = ["Golden", "Big", "Ginormous"] },
    { name = "Axolotl", color = "F1A1FF", description = "Look at how cute it is!! :3 :3", base_value = 20, possible_modifiers = ["Big", "Prismatic"] },
]
fishes_modifiers = [
    { name = "Ginormous", description = "A very big fish :D", chance = 100, value_multiplier = 5, size_multiplier = 20 },
    { name = "Big", description = "A big fish :)", chance = 10, value_multiplier = 3, size_multiplier = 5 },
    { name = "Golden", description = "Woahh!~ Shiny!!", chance = 500, value_multiplier = 100 },
    { name = "Rotten", description = "Ew.", chance = 50, value_multiplier = 0.5 },
    { name = "Prismatic", description = "WOWIE! A rainbow-looking creature!", chance = 1000, value_multiplier = 150 },
]